# Use the official Nginx image from the Docker Hub
FROM nginx:latest

# Copy the content of the current directory to /usr/share/nginx/html in the container
COPY . /usr/share/nginx/html

# Expose port 80 to allow external access
EXPOSE 80